services:
  sandman_main:
    image: sandman/sandman_main
    build: 
      context: .
      dockerfile: Dockerfile
    
    container_name: sandman_main
    group_add:
      - ${GPIO_GID}
    volumes:
      - ~:/home/app
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
    networks:
      - sandman_network
    environment:
      - RHASSPY_HOSTNAME=rhasspy

networks:
  sandman_network:
    name: sandman_network
    external: true
